// frontend/src/components/LogViewer.jsx
import { useEffect, useState } from "react";
import { api } from "../api/client";
import { Icon } from "./Icon";

function toLocalDatetimeString(date) {
  const d = new Date(date);
  const pad = (n) => String(n).padStart(2, "0");
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;
}

export function LogViewer({ server, notify }) {
  const [services, setServices] = useState([]);
  const [service, setService] = useState("");
  const [source, setSource] = useState("journal");
  const [dateFrom, setDateFrom] = useState(() => {
    const d = new Date(Date.now() - 3600000);
    return toLocalDatetimeString(d);
  });
  const [dateTo, setDateTo] = useState(() => toLocalDatetimeString(new Date()));
  const [filePath, setFilePath] = useState("");
  const [grep, setGrep] = useState("");
  const [lines, setLines] = useState([]);
  const [total, setTotal] = useState(0);
  const [truncated, setTruncated] = useState(false);
  const [loading, setLoading] = useState(false);
  const [loaded, setLoaded] = useState(false);

  useEffect(() => {
    let active = true;
    api.logServices().then((items) => { if (active) setServices(items); }).catch((err) => { if (active) notify(err.message, "error"); });
    return () => { active = false; };
  }, [notify]);

  const selectedService = services.find((s) => s.id === service);

  useEffect(() => {
    if (selectedService && selectedService.files.length > 0) {
      setFilePath(selectedService.files[0]);
    } else {
      setFilePath("");
    }
  }, [selectedService]);

  useEffect(() => {
    if (selectedService) {
      setSource(selectedService.journal_unit ? "journal" : "file");
    }
  }, [selectedService]);

  async function fetchLogs() {
    if (!service) {
      notify("Выберите сервис", "error");
      return;
    }
    setLoading(true);
    setLoaded(false);
    try {
      const result = await api.logs(server.id, {
        service,
        source,
        date_from: new Date(dateFrom).toISOString(),
        date_to: new Date(dateTo).toISOString(),
        file_path: source === "file" ? filePath : null,
        grep: grep || null,
        limit: 5000,
      });
      setLines(result.lines);
      setTotal(result.total);
      setTruncated(result.truncated);
      setLoaded(true);
    } catch (err) {
      notify(err.message, "error");
    } finally {
      setLoading(false);
    }
  }

  function downloadLogs() {
    if (!lines.length) return;
    const blob = new Blob([lines.join("\n")], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${server.name}_${service}_${new Date().toISOString().slice(0, 10)}.log`;
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div className="log-viewer">
      <div className="log-controls">
        <label>
          Сервис
          <select value={service} onChange={(e) => setService(e.target.value)} required>
            <option value="">Выберите сервис</option>
            {services.map((s) => (
              <option key={s.id} value={s.id}>{s.name}</option>
            ))}
          </select>
        </label>

        <label>
          Источник
          <select value={source} onChange={(e) => setSource(e.target.value)}>
            <option value="journal" disabled={!selectedService?.journal_unit}>journalctl</option>
            <option value="file">Файл лога</option>
          </select>
        </label>

        {source === "file" && selectedService?.files?.length > 0 && (
          <label>
            Файл
            <select value={filePath} onChange={(e) => setFilePath(e.target.value)}>
              {selectedService.files.map((f) => (
                <option key={f} value={f}>{f}</option>
              ))}
            </select>
          </label>
        )}

        <label>
          С
          <input
            type="datetime-local"
            value={dateFrom}
            onChange={(e) => setDateFrom(e.target.value)}
          />
        </label>

        <label>
          По
          <input
            type="datetime-local"
            value={dateTo}
            onChange={(e) => setDateTo(e.target.value)}
          />
        </label>

        <label>
          Фильтр
          <input
            type="text"
            value={grep}
            onChange={(e) => setGrep(e.target.value)}
            placeholder="grep шаблон"
          />
        </label>

        <div className="log-controls__actions">
          <button className="button button--primary" onClick={fetchLogs} disabled={loading || !service}>
            {loading ? "Загружаем…" : "Загрузить логи"}
          </button>
          {loaded && lines.length > 0 && (
            <button className="button" onClick={downloadLogs}>
              <Icon name="snapshot" size={16} /> Скачать
            </button>
          )}
        </div>
      </div>

      {loaded && (
        <div className="log-info">
          <span>Строк: {total}</span>
          {truncated && <span className="log-info__warn"> (ограничено 5000 строк)</span>}
          <span> · Источник: {lines[0]?.includes("journalctl") ? "journalctl" : source}</span>
        </div>
      )}

      <div className="log-output">
        {loading ? (
          <div className="log-loading">
            <div className="skeleton-list"><i/><i/><i/><i/><i/></div>
          </div>
        ) : loaded && lines.length > 0 ? (
          <pre className="log-pre">{lines.join("\n")}</pre>
        ) : loaded ? (
          <div className="log-empty">Логи не найдены за выбранный период</div>
        ) : (
          <div className="log-empty">Выберите сервис и период для загрузки логов</div>
        )}
      </div>
    </div>
  );
}

// frontend/src/components/LogViewer.vue
<script setup>
import { ref, computed, watch, onMounted } from "vue";
import { api } from "../api/client";
import DownloadIcon from "@bitrix24/b24icons-vue/outline/DownloadIcon";
import RefreshIcon from "@bitrix24/b24icons-vue/outline/RefreshIcon";

const props = defineProps({
  server: {
    type: Object,
    required: true,
  },
});

const toast = useToast();

function toLocalDatetimeString(date) {
  const d = new Date(date);
  const pad = (n) => String(n).padStart(2, "0");
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;
}

const services = ref([]);
const service = ref("");
const source = ref("journal");
const dateFrom = ref(toLocalDatetimeString(Date.now() - 3600000));
const dateTo = ref(toLocalDatetimeString(Date.now()));
const filePath = ref("");
const grep = ref("");
const lines = ref([]);
const total = ref(0);
const truncated = ref(false);
const loading = ref(false);
const loaded = ref(false);

onMounted(async () => {
  try {
    services.value = await api.logServices();
    if (services.value.length > 0 && !service.value) {
      service.value = services.value[0].id;
    }
  } catch (err) {
    toast.add({
      title: "Ошибка загрузки сервисов",
      description: err.message,
      color: "air-primary-alert",
    });
  }
});

const selectedService = computed(() =>
  services.value.find((s) => s.id === service.value)
);

const serviceOptions = computed(() =>
  services.value.map((s) => ({ label: s.name, value: s.id }))
);

const sourceOptions = computed(() => {
  const opts = [];
  if (selectedService.value?.journal_unit) {
    opts.push({ label: "journalctl", value: "journal" });
  }
  opts.push({ label: "Файл лога", value: "file" });
  return opts;
});

const fileOptions = computed(() =>
  (selectedService.value?.files || []).map((f) => ({ label: f, value: f }))
);

watch(selectedService, (s) => {
  if (s && s.files.length > 0) {
    filePath.value = s.files[0];
  } else {
    filePath.value = "";
  }
  if (s) {
    source.value = s.journal_unit ? "journal" : "file";
  }
});

async function fetchLogs() {
  if (!service.value) {
    toast.add({
      title: "Выберите сервис",
      color: "air-primary-warning",
    });
    return;
  }

  loading.value = true;
  loaded.value = false;
  try {
    const result = await api.logs(props.server.id, {
      service: service.value,
      source: source.value,
      date_from: new Date(dateFrom.value).toISOString(),
      date_to: new Date(dateTo.value).toISOString(),
      file_path: source.value === "file" ? filePath.value : null,
      grep: grep.value || null,
      limit: 5000,
    });
    lines.value = result.lines || [];
    total.value = result.total || 0;
    truncated.value = result.truncated || false;
    loaded.value = true;
  } catch (err) {
    toast.add({
      title: "Ошибка получения логов",
      description: err.message,
      color: "air-primary-alert",
    });
  } finally {
    loading.value = false;
  }
}

function downloadLogs() {
  if (!lines.value.length) return;
  const blob = new Blob([lines.value.join("\n")], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${props.server.name}_${service.value}_${new Date().toISOString().slice(0, 10)}.log`;
  a.click();
  URL.revokeObjectURL(url);
}
</script>

<template>
  <div class="space-y-4">
    <!-- Controls Bar -->
    <div class="p-4 rounded-xl bg-elevated/50 border border-muted space-y-4">
      <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <!-- Service -->
        <B24FormField label="Сервис" required>
          <B24Select
            v-model="service"
            :items="serviceOptions"
            placeholder="Выберите сервис"
            class="w-full"
          />
        </B24FormField>

        <!-- Source -->
        <B24FormField label="Источник">
          <B24Select
            v-model="source"
            :items="sourceOptions"
            class="w-full"
          />
        </B24FormField>

        <!-- Date From -->
        <B24FormField label="С даты">
          <B24Input
            v-model="dateFrom"
            type="datetime-local"
            class="w-full"
          />
        </B24FormField>

        <!-- Date To -->
        <B24FormField label="По дату">
          <B24Input
            v-model="dateTo"
            type="datetime-local"
            class="w-full"
          />
        </B24FormField>
      </div>

      <div class="grid grid-cols-1 sm:grid-cols-3 gap-4 items-end">
        <!-- Log File (if file source) -->
        <div v-if="source === 'file' && fileOptions.length > 0" class="sm:col-span-1">
          <B24FormField label="Файл">
            <B24Select
              v-model="filePath"
              :items="fileOptions"
              class="w-full font-mono text-xs"
            />
          </B24FormField>
        </div>

        <!-- Grep Pattern -->
        <div :class="source === 'file' && fileOptions.length > 0 ? 'sm:col-span-1' : 'sm:col-span-2'">
          <B24FormField label="Grep фильтр">
            <B24Input
              v-model="grep"
              placeholder="Шаблон регулярного выражения или подстрока"
              class="w-full font-mono text-xs"
            />
          </B24FormField>
        </div>

        <!-- Action Buttons -->
        <div class="flex items-center gap-2 justify-end">
          <B24Button
            label="Загрузить логи"
            :icon="RefreshIcon"
            color="air-primary"
            :loading="loading"
            @click="fetchLogs"
          />
          <B24Button
            v-if="loaded && lines.length > 0"
            label="Скачать"
            :icon="DownloadIcon"
            color="air-secondary-no-accent"
            variant="outline"
            @click="downloadLogs"
          />
        </div>
      </div>
    </div>

    <!-- Info bar -->
    <div v-if="loaded" class="flex items-center justify-between px-2 text-xs text-muted">
      <span>Найдено строк: <b class="text-label">{{ total }}</b></span>
      <span v-if="truncated" class="text-[var(--ui-color-design-filled-amber)]">
        (Вывод ограничен первыми 5000 строками)
      </span>
      <span>Источник: <code class="font-mono text-xs">{{ lines[0]?.includes("journalctl") ? "journalctl" : source }}</code></span>
    </div>

    <!-- Terminal Output -->
    <div class="rounded-xl border border-muted bg-elevated/80 overflow-hidden shadow-inner min-h-[320px]">
      <div v-if="loading" class="p-8 text-center text-sm text-muted">
        Загрузка журнала событий…
      </div>

      <div v-else-if="loaded && lines.length > 0" class="p-4 max-h-[560px] overflow-auto">
        <pre class="terminal-output text-xs font-mono text-description leading-relaxed whitespace-pre-wrap break-all select-all">{{ lines.join('\n') }}</pre>
      </div>

      <div v-else-if="loaded" class="p-12 text-center text-sm text-muted">
        Записи в журнале за указанный период не найдены
      </div>

      <div v-else class="p-12 text-center text-sm text-muted">
        Выберите сервис, временной интервал и нажмите «Загрузить логи»
      </div>
    </div>
  </div>
</template>
