// frontend/src/components/ServerWorkspace.jsx
import { useEffect, useMemo, useState } from "react";
import { api } from "../api/client";
import { Icon } from "./Icon";
import { ActionDialog } from "./ActionDialog";
import { AddServerDialog } from "./AddServerDialog";
import { LogViewer } from "./LogViewer";
import { Modal } from "./Modal";

const riskLabels = { low: "Низкий", medium: "Средний", high: "Высокий", critical: "Критический" };
const categoryLabels = { pool: "Пул", hosts: "Хосты", local: "Система", runtime: "Платформа", mysql: "MySQL", memcached: "Memcached", tasks: "Задачи", sites: "Сайты", site: "Сайты", sphinx: "Sphinx", web: "Web / PHP", monitoring: "Мониторинг", push: "Push", transformer: "Трансформер" };
const summaryTranslations = { "Create the native Bitrix server pool": "Создать пул Bitrix", "Remove the native Bitrix server pool": "Удалить пул Bitrix", "Reboot the BitrixVM server": "Перезагрузить сервер", "Power off the BitrixVM server": "Выключить сервер", "Update all EL9 packages": "Обновить системные пакеты", "Create memcached instance": "Создать экземпляр Memcached", "Stop a Bitrix background task": "Остановить фоновую задачу", "Create a Bitrix kernel site": "Создать сайт с ядром Bitrix", "Configure Node.js push service": "Настроить Push-сервис" };

const relativeTime = (date) => {
  if (!date) return "Не проверялся";
  const minutes = Math.max(0, Math.round((Date.now() - new Date(date).getTime()) / 60000));
  if (minutes < 1) return "только что";
  if (minutes < 60) return `${minutes} мин назад`;
  if (minutes < 1440) return `${Math.round(minutes / 60)} ч назад`;
  return new Date(date).toLocaleDateString("ru-RU");
};

export function ServerWorkspace({ servers, setServers, operations, setOperations, notify, navigateOperations }) {
  const [selectedId, setSelectedId] = useState(servers[0]?.id || null);
  const [capabilities, setCapabilities] = useState([]);
  const [search, setSearch] = useState("");
  const [actionSearch, setActionSearch] = useState("");
  const [category, setCategory] = useState("all");
  const [loadingCapabilities, setLoadingCapabilities] = useState(false);
  const [addOpen, setAddOpen] = useState(false);
  const [activeAction, setActiveAction] = useState(null);
  const [snapshot, setSnapshot] = useState(null);
  const [snapshotLoading, setSnapshotLoading] = useState(false);
  const [activeTab, setActiveTab] = useState("capabilities");
  const selected = servers.find((item) => item.id === selectedId) || servers[0];

  useEffect(() => {
    if (!selected) { setCapabilities([]); return; }
    let active = true; setLoadingCapabilities(true);
    api.capabilities(selected.id).then((items) => { if (active) setCapabilities(items); }).catch((error) => notify(error.message, "error")).finally(() => active && setLoadingCapabilities(false));
    return () => { active = false; };
  }, [selected?.id]);

  const visibleServers = useMemo(() => servers.filter((server) => `${server.name} ${server.address}`.toLowerCase().includes(search.toLowerCase())), [servers, search]);
  const categories = useMemo(() => [...new Set(capabilities.map((item) => item.category))], [capabilities]);
  const visibleCapabilities = useMemo(() => capabilities.filter((item) => (category === "all" || item.category === category) && `${item.action} ${item.summary || ""}`.toLowerCase().includes(actionSearch.toLowerCase())), [capabilities, category, actionSearch]);

  async function refreshCapabilities() {
    if (!selected) return; setLoadingCapabilities(true);
    try { setCapabilities(await api.refreshCapabilities(selected.id)); notify("Возможности сервера обновлены"); setServers((items) => items.map((item) => item.id === selected.id ? { ...item, capabilities_checked_at: new Date().toISOString() } : item)); }
    catch (error) { notify(error.message, "error"); } finally { setLoadingCapabilities(false); }
  }

  async function loadSnapshot() {
    setSnapshotLoading(true);
    try { setSnapshot(await api.snapshot(selected.id)); } catch (error) { notify(error.message, "error"); } finally { setSnapshotLoading(false); }
  }

  if (!servers.length) return <section className="page"><PageHeader search={search} setSearch={setSearch} onAdd={() => setAddOpen(true)} /><div className="empty-state"><div className="empty-state__icon"><Icon name="servers" size={30}/></div><h2>Добавьте первый сервер</h2><p>Контроллер проверит SSH fingerprint и совместимость BitrixEnv перед сохранением.</p><button className="button button--primary" onClick={() => setAddOpen(true)}><Icon name="plus"/> Добавить сервер</button></div>{addOpen ? <AddServerDialog onClose={() => setAddOpen(false)} onCreated={(server) => { setServers([server]); setSelectedId(server.id); }} notify={notify}/> : null}</section>;

  return <section className="page page--servers">
    <PageHeader search={search} setSearch={setSearch} onAdd={() => setAddOpen(true)} />
    <div className="server-workspace">
      <div className="server-list panel">
        <div className="table-head server-grid"><span>Сервер</span><span>Адрес</span><span>Состояние</span><span>Проверка</span></div>
        <div className="server-rows">{visibleServers.map((server) => <button key={server.id} className={`server-row server-grid ${selected?.id === server.id ? "selected" : ""}`} onClick={() => setSelectedId(server.id)}><span className="server-name"><Icon name="servers" size={18}/><b>{server.name}</b></span><code>{server.address}</code><span className={Date.now() - new Date(server.capabilities_checked_at).getTime() > 7200000 ? "status status--warn" : "status status--ok"}><i/>{Date.now() - new Date(server.capabilities_checked_at).getTime() > 7200000 ? "Проверить" : "Доступен"}</span><span>{relativeTime(server.capabilities_checked_at)}</span></button>)}</div>
        {!visibleServers.length ? <div className="inline-empty">Серверы не найдены</div> : null}
      </div>
      <div className="server-detail panel">
        <header className="detail-header"><div><h2>{selected.name}</h2><span className="status status--ok"><i/>Доступен</span></div><div className="button-group"><button className="button button--small" onClick={refreshCapabilities} disabled={loadingCapabilities}><Icon name="refresh"/>{loadingCapabilities ? "Обновляем…" : "Обновить"}</button><button className="button button--small" onClick={loadSnapshot} disabled={snapshotLoading}><Icon name="snapshot"/>{snapshotLoading ? "Собираем…" : "Снимок"}</button></div></header>
        <dl className="server-meta"><dt>Адрес</dt><dd><code>{selected.address}:{selected.port}</code></dd><dt>Пользователь</dt><dd>{selected.username}</dd><dt>SSH fingerprint</dt><dd><code title={selected.host_key_fingerprint}>{selected.host_key_fingerprint.slice(0, 29)}…</code></dd><dt>Возможности получены</dt><dd>{relativeTime(selected.capabilities_checked_at)}</dd></dl>
        <div className="tabs" role="tablist"><button className={activeTab === "capabilities" ? "active" : ""} onClick={() => setActiveTab("capabilities")}>Возможности <span>{capabilities.filter((item) => item.available).length}</span></button><button className={activeTab === "snapshot" ? "active" : ""} onClick={() => { setActiveTab("snapshot"); loadSnapshot(); }}>Состояние</button><button className={activeTab === "logs" ? "active" : ""} onClick={() => setActiveTab("logs")}>Логи</button><button className={activeTab === "operations" ? "active" : ""} onClick={() => { setActiveTab("operations"); navigateOperations(); }}>История</button></div>
        {activeTab === "capabilities" && <>
        <div className="capability-tools"><div className="search search--compact"><Icon name="search"/><input value={actionSearch} onChange={(event) => setActionSearch(event.target.value)} placeholder="Найти действие" aria-label="Найти действие" /></div><select value={category} onChange={(event) => setCategory(event.target.value)} aria-label="Категория"><option value="all">Все категории</option>{categories.map((item) => <option value={item} key={item}>{categoryLabels[item] || item}</option>)}</select></div>
        <div className="capability-table"><div className="capability-head"><span>Действие</span><span>Описание</span><span>Риск</span><span>Доступность</span><span/></div>{loadingCapabilities ? <div className="skeleton-list"><i/><i/><i/><i/></div> : visibleCapabilities.map((item) => <div className={`capability-row ${!item.available ? "disabled" : ""}`} key={item.action}><code>{item.action}</code><span>{summaryTranslations[item.summary] || item.summary || categoryLabels[item.category] || "Системное действие"}{item.reason ? <small>Причина: {item.reason}</small> : null}</span><span className={`risk risk--${item.risk}`}><i/>{riskLabels[item.risk]}</span><span className={item.available ? "available" : "unavailable"}>{item.available ? "Доступно" : "Недоступно"}</span><button className="button button--outline button--tiny" disabled={!item.available} onClick={() => setActiveAction({ ...item, summary: summaryTranslations[item.summary] || item.summary || item.action })}>Открыть</button></div>)}</div>
        {!loadingCapabilities && !visibleCapabilities.length ? <div className="inline-empty">Подходящие действия не найдены</div> : null}
        </>}
        {activeTab === "snapshot" && <>
        {snapshot ? <div className="snapshot"><pre>{JSON.stringify(snapshot, null, 2)}</pre></div> : <div className="inline-empty">{snapshotLoading ? "Загружаем снимок…" : "Нажмите «Состояние» для загрузки"}</div>}
        </>}
        {activeTab === "logs" && <LogViewer server={selected} notify={notify} />}
      </div>
    </div>
    <section className="recent panel"><header><h2>Последние операции</h2><button onClick={navigateOperations}>Все операции <Icon name="chevron" size={17}/></button></header>{operations.slice(0, 3).map((operation) => <div className="recent-row" key={operation.id}><code>{operation.action}</code><span>{servers.find((server) => server.id === operation.server_id)?.name || "—"}</span><OperationStatus status={operation.status}/><time>{new Date(operation.created_at).toLocaleTimeString("ru-RU", { hour: "2-digit", minute: "2-digit" })}</time></div>)}</section>
    {addOpen ? <AddServerDialog onClose={() => setAddOpen(false)} onCreated={(server) => { setServers((items) => [...items, server]); setSelectedId(server.id); }} notify={notify}/> : null}
    {activeAction ? <ActionDialog server={selected} capability={activeAction} onClose={() => setActiveAction(null)} onExecuted={(operation) => setOperations((items) => [operation, ...items])} notify={notify}/> : null}
  </section>;
}

function PageHeader({ search, setSearch, onAdd }) { return <header className="page-header"><div><h1>Серверы</h1><p>Управление инфраструктурой BitrixEnv</p></div><div className="page-actions"><div className="search"><Icon name="search"/><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Поиск по серверам" aria-label="Поиск по серверам" /></div><button className="button button--primary" onClick={onAdd}><Icon name="plus"/>Добавить сервер</button></div></header>; }

export function OperationStatus({ status }) { const labels = { queued: "В очереди", running: "Выполняется", succeeded: "Выполнено", failed: "Ошибка", canceled: "Отменено", unknown: "Неизвестно" }; return <span className={`op-status op-status--${status}`}><i/>{labels[status] || status}</span>; }

// frontend/src/views/ServerWorkspace.vue
<script setup>
import { ref, computed, watch, onMounted } from "vue";
import { useRouter } from "vue-router";
import { api } from "../api/client";
import { useAppContext } from "../composables/useAppContext";
import AddServerDialog from "../components/AddServerDialog.vue";
import ActionDialog from "../components/ActionDialog.vue";
import LogViewer from "../components/LogViewer.vue";
import DeveloperResourcesIcon from "@bitrix24/b24icons-vue/outline/DeveloperResourcesIcon";
import PlusLIcon from "@bitrix24/b24icons-vue/outline/PlusLIcon";
import RefreshIcon from "@bitrix24/b24icons-vue/outline/RefreshIcon";
import FileIcon from "@bitrix24/b24icons-vue/outline/FileIcon";
import SearchIcon from "@bitrix24/b24icons-vue/outline/SearchIcon";
import ChevronRightLIcon from "@bitrix24/b24icons-vue/outline/ChevronRightLIcon";

const router = useRouter();
const toast = useToast();
const { servers, operations, fetchServers, fetchOperations } = useAppContext();

const riskLabels = {
  low: "Низкий",
  medium: "Средний",
  high: "Высокий",
  critical: "Критический",
};

const categoryLabels = {
  pool: "Пул",
  hosts: "Хосты",
  local: "Система",
  runtime: "Платформа",
  mysql: "MySQL",
  memcached: "Memcached",
  tasks: "Задачи",
  sites: "Сайты",
  site: "Сайты",
  sphinx: "Sphinx",
  web: "Web / PHP",
  monitoring: "Мониторинг",
  push: "Push",
  transformer: "Трансформер",
};

const summaryTranslations = {
  "Create the native Bitrix server pool": "Создать пул Bitrix",
  "Remove the native Bitrix server pool": "Удалить пул Bitrix",
  "Reboot the BitrixVM server": "Перезагрузить сервер",
  "Power off the BitrixVM server": "Выключить сервер",
  "Update all EL9 packages": "Обновить системные пакеты",
  "Create memcached instance": "Создать экземпляр Memcached",
  "Stop a Bitrix background task": "Остановить фоновую задачу",
  "Create a Bitrix kernel site": "Создать сайт с ядром Bitrix",
  "Configure Node.js push service": "Настроить Push-сервис",
};

function relativeTime(date) {
  if (!date) return "Не проверялся";
  const minutes = Math.max(0, Math.round((Date.now() - new Date(date).getTime()) / 60000));
  if (minutes < 1) return "только что";
  if (minutes < 60) return `${minutes} мин назад`;
  if (minutes < 1440) return `${Math.round(minutes / 60)} ч назад`;
  return new Date(date).toLocaleDateString("ru-RU");
}

const selectedId = ref(null);
const capabilities = ref([]);
const search = ref("");
const actionSearch = ref("");
const category = ref("all");
const loadingCapabilities = ref(false);
const addOpen = ref(false);
const activeAction = ref(null);
const actionDialogOpen = ref(false);
const snapshot = ref(null);
const snapshotLoading = ref(false);
const activeTab = ref("capabilities");

const selected = computed(() => {
  return servers.value.find((item) => item.id === selectedId.value) || servers.value[0] || null;
});

onMounted(async () => {
  await fetchServers();
  if (servers.value.length > 0 && !selectedId.value) {
    selectedId.value = servers.value[0].id;
  }
});

watch(
  () => servers.value,
  (list) => {
    if (list.length > 0 && (!selectedId.value || !list.some((s) => s.id === selectedId.value))) {
      selectedId.value = list[0].id;
    }
  },
  { immediate: true }
);

watch(
  () => selected.value?.id,
  async (id) => {
    if (!id) {
      capabilities.value = [];
      return;
    }
    loadingCapabilities.value = true;
    try {
      capabilities.value = await api.capabilities(id);
    } catch (err) {
      toast.add({
        title: "Ошибка загрузки возможностей",
        description: err.message,
        color: "air-primary-alert",
      });
    } finally {
      loadingCapabilities.value = false;
    }
  },
  { immediate: true }
);

const visibleServers = computed(() =>
  servers.value.filter((server) =>
    `${server.name} ${server.address}`.toLowerCase().includes(search.value.toLowerCase())
  )
);

const categories = computed(() => [
  ...new Set(capabilities.value.map((item) => item.category)),
]);

const categoryOptions = computed(() => [
  { label: "Все категории", value: "all" },
  ...categories.value.map((cat) => ({
    label: categoryLabels[cat] || cat,
    value: cat,
  })),
]);

const visibleCapabilities = computed(() =>
  capabilities.value.filter(
    (item) =>
      (category.value === "all" || item.category === category.value) &&
      `${item.action} ${item.summary || ""}`.toLowerCase().includes(actionSearch.value.toLowerCase())
  )
);

async function refreshCapabilities() {
  if (!selected.value) return;
  loadingCapabilities.value = true;
  try {
    capabilities.value = await api.refreshCapabilities(selected.value.id);
    toast.add({
      title: "Возможности обновлены",
      color: "air-primary-success",
    });
    await fetchServers();
  } catch (err) {
    toast.add({
      title: "Ошибка обновления возможностей",
      description: err.message,
      color: "air-primary-alert",
    });
  } finally {
    loadingCapabilities.value = false;
  }
}

async function loadSnapshot() {
  if (!selected.value) return;
  snapshotLoading.value = true;
  try {
    snapshot.value = await api.snapshot(selected.value.id);
  } catch (err) {
    toast.add({
      title: "Ошибка получения снимка",
      description: err.message,
      color: "air-primary-alert",
    });
  } finally {
    snapshotLoading.value = false;
  }
}

function openAction(item) {
  activeAction.value = {
    ...item,
    summary: summaryTranslations[item.summary] || item.summary || item.action,
  };
  actionDialogOpen.value = true;
}

function handleServerCreated(newServer) {
  fetchServers();
  selectedId.value = newServer.id;
}

function handleActionExecuted(operation) {
  fetchOperations();
}

const tabItems = computed(() => [
  {
    value: "capabilities",
    label: `Возможности (${capabilities.value.filter((i) => i.available).length})`,
  },
  {
    value: "snapshot",
    label: "Состояние",
  },
  {
    value: "logs",
    label: "Логи",
  },
  {
    value: "history",
    label: "История",
  },
]);

function handleTabChange(tab) {
  activeTab.value = tab;
  if (tab === "snapshot" && !snapshot.value) {
    loadSnapshot();
  } else if (tab === "history") {
    router.push("/operations");
  }
}
</script>

<template>
  <div class="space-y-6">
    <!-- Page Header -->
    <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
      <div>
        <h1 class="text-2xl font-bold text-label tracking-tight">Серверы</h1>
        <p class="text-sm text-muted mt-1">Управление инфраструктурой и действиями BitrixEnv</p>
      </div>

      <div class="flex items-center gap-3">
        <div class="w-64">
          <B24Input
            v-model="search"
            :icon="SearchIcon"
            placeholder="Поиск по серверам…"
            class="w-full"
          />
        </div>
        <B24Button
          :icon="PlusLIcon"
          label="Добавить сервер"
          color="air-primary"
          @click="addOpen = true"
        />
      </div>
    </div>

    <!-- If no servers exist -->
    <B24Card v-if="!servers.length" class="p-12 text-center border border-muted">
      <div class="max-w-md mx-auto space-y-4">
        <div class="p-4 rounded-2xl bg-elevated border border-muted inline-block">
          <DeveloperResourcesIcon class="size-12 text-[var(--ui-color-design-filled-blue)]" />
        </div>
        <h2 class="text-xl font-bold text-label">Добавьте первый сервер</h2>
        <p class="text-sm text-description">
          Контроллер проверит SSH fingerprint и совместимость BitrixEnv перед сохранением в контур.
        </p>
        <B24Button
          label="Добавить сервер"
          :icon="PlusLIcon"
          color="air-primary"
          @click="addOpen = true"
        />
      </div>
    </B24Card>

    <!-- Workspace Master/Detail -->
    <div v-else class="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
      <!-- Left Panel: Servers List -->
      <B24Card class="lg:col-span-5 border border-muted overflow-hidden flex flex-col">
        <template #header>
          <div class="flex items-center justify-between text-xs font-semibold text-muted uppercase tracking-wider">
            <span>Сервер</span>
            <span>Статус</span>
          </div>
        </template>

        <div v-if="visibleServers.length" class="divide-y divide-muted">
          <div
            v-for="server in visibleServers"
            :key="server.id"
            class="p-4 flex items-center justify-between cursor-pointer transition-colors"
            :class="selected?.id === server.id ? 'bg-accented/60 border-l-4 border-l-[var(--ui-color-design-filled-blue)]' : 'hover:bg-muted/30'"
            @click="selectedId = server.id"
          >
            <div class="min-w-0 space-y-1">
              <div class="flex items-center gap-2">
                <DeveloperResourcesIcon class="size-4 text-[var(--ui-color-design-filled-blue)] shrink-0" />
                <span class="font-bold text-sm text-label truncate">{{ server.name }}</span>
              </div>
              <p class="text-xs text-muted font-mono truncate">{{ server.address }}:{{ server.port }}</p>
            </div>

            <div class="flex flex-col items-end gap-1 shrink-0">
              <B24Badge
                :label="Date.now() - new Date(server.capabilities_checked_at).getTime() > 7200000 ? 'Проверить' : 'Доступен'"
                :color="Date.now() - new Date(server.capabilities_checked_at).getTime() > 7200000 ? 'air-primary-warning' : 'air-primary-success'"
                size="sm"
              />
              <span class="text-[11px] text-muted">{{ relativeTime(server.capabilities_checked_at) }}</span>
            </div>
          </div>
        </div>

        <div v-else class="p-8 text-center text-sm text-muted">
          Серверы по запросу не найдены
        </div>
      </B24Card>

      <!-- Right Panel: Server Detail -->
      <B24Card v-if="selected" class="lg:col-span-7 border border-muted space-y-6">
        <template #header>
          <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-4 w-full">
            <div class="flex items-center gap-3">
              <h2 class="text-xl font-bold text-label">{{ selected.name }}</h2>
              <B24Badge label="Доступен" color="air-primary-success" size="sm" />
            </div>

            <div class="flex items-center gap-2">
              <B24Button
                label="Обновить"
                :icon="RefreshIcon"
                color="air-secondary-no-accent"
                variant="outline"
                size="sm"
                :loading="loadingCapabilities"
                @click="refreshCapabilities"
              />
              <B24Button
                label="Снимок"
                :icon="FileIcon"
                color="air-secondary-no-accent"
                variant="outline"
                size="sm"
                :loading="snapshotLoading"
                @click="loadSnapshot"
              />
            </div>
          </div>
        </template>

        <!-- Meta list -->
        <div class="grid grid-cols-2 sm:grid-cols-4 gap-4 p-4 rounded-xl bg-elevated/50 border border-muted text-xs">
          <div>
            <span class="text-muted block">Адрес</span>
            <span class="font-mono text-label block mt-0.5">{{ selected.address }}:{{ selected.port }}</span>
          </div>
          <div>
            <span class="text-muted block">Пользователь</span>
            <span class="font-medium text-label block mt-0.5">{{ selected.username }}</span>
          </div>
          <div>
            <span class="text-muted block">SSH fingerprint</span>
            <span class="font-mono text-label block mt-0.5 truncate" :title="selected.host_key_fingerprint">
              {{ selected.host_key_fingerprint?.slice(0, 20) }}…
            </span>
          </div>
          <div>
            <span class="text-muted block">Проверен</span>
            <span class="text-label block mt-0.5">{{ relativeTime(selected.capabilities_checked_at) }}</span>
          </div>
        </div>

        <!-- Custom Tabs Switcher -->
        <div class="flex items-center gap-2 border-b border-muted pb-2">
          <B24Button
            v-for="tab in tabItems"
            :key="tab.value"
            :label="tab.label"
            :variant="activeTab === tab.value ? 'solid' : 'ghost'"
            :color="activeTab === tab.value ? 'air-primary' : 'air-secondary-no-accent'"
            size="sm"
            @click="handleTabChange(tab.value)"
          />
        </div>

        <!-- Tab 1: Capabilities -->
        <div v-if="activeTab === 'capabilities'" class="space-y-4">
          <!-- Filters -->
          <div class="flex flex-col sm:flex-row items-center gap-3">
            <div class="flex-1 w-full">
              <B24Input
                v-model="actionSearch"
                :icon="SearchIcon"
                placeholder="Найти действие (например reboot, site, mysql)…"
                class="w-full"
              />
            </div>
            <div class="w-full sm:w-48">
              <B24Select
                v-model="category"
                :items="categoryOptions"
                class="w-full"
              />
            </div>
          </div>

          <!-- Actions Table -->
          <div class="rounded-xl border border-muted overflow-hidden">
            <div v-if="loadingCapabilities" class="p-8 text-center text-sm text-muted">
              Загрузка доступных действий…
            </div>

            <div v-else-if="visibleCapabilities.length" class="divide-y divide-muted">
              <div
                v-for="item in visibleCapabilities"
                :key="item.action"
                class="p-3.5 flex flex-col sm:flex-row sm:items-center justify-between gap-3 hover:bg-muted/30 transition-colors"
                :class="{ 'opacity-60': !item.available }"
              >
                <div class="min-w-0 space-y-1">
                  <div class="flex items-center gap-2">
                    <code class="text-xs font-bold text-label font-mono">{{ item.action }}</code>
                    <B24Badge
                      :label="riskLabels[item.risk] || item.risk"
                      :color="item.risk === 'high' || item.risk === 'critical' ? 'air-primary-alert' : item.risk === 'medium' ? 'air-primary-warning' : 'air-primary-success'"
                      size="xs"
                    />
                  </div>
                  <p class="text-xs text-description">
                    {{ summaryTranslations[item.summary] || item.summary || categoryLabels[item.category] || "Системное действие" }}
                  </p>
                  <p v-if="item.reason" class="text-[11px] text-[var(--ui-color-design-filled-amber)]">
                    Недоступно: {{ item.reason }}
                  </p>
                </div>

                <div class="flex items-center gap-3 shrink-0 self-end sm:self-center">
                  <B24Badge
                    :label="item.available ? 'Доступно' : 'Недоступно'"
                    :color="item.available ? 'air-primary-success' : 'air-secondary-no-accent'"
                    size="xs"
                  />
                  <B24Button
                    label="Открыть"
                    color="air-primary"
                    variant="outline"
                    size="xs"
                    :disabled="!item.available"
                    @click="openAction(item)"
                  />
                </div>
              </div>
            </div>

            <div v-else class="p-8 text-center text-sm text-muted">
              Действия по указанным критериям не найдены
            </div>
          </div>
        </div>

        <!-- Tab 2: Snapshot -->
        <div v-else-if="activeTab === 'snapshot'" class="space-y-4">
          <div v-if="snapshot" class="p-4 rounded-xl bg-elevated border border-muted overflow-auto max-h-[460px]">
            <pre class="terminal-output text-xs font-mono text-description whitespace-pre-wrap">{{ JSON.stringify(snapshot, null, 2) }}</pre>
          </div>
          <div v-else class="p-8 text-center text-sm text-muted">
            {{ snapshotLoading ? 'Сбор диагностического снимка…' : 'Нажмите «Снимок» для загрузки состояния' }}
          </div>
        </div>

        <!-- Tab 3: Logs -->
        <div v-else-if="activeTab === 'logs'">
          <LogViewer :server="selected" />
        </div>
      </B24Card>
    </div>

    <!-- Recent Operations Strip -->
    <B24Card class="border border-muted">
      <template #header>
        <div class="flex items-center justify-between">
          <h3 class="font-bold text-label text-base">Последние операции</h3>
          <B24Button
            label="Все операции"
            :trailing-icon="ChevronRightLIcon"
            variant="link"
            color="air-primary"
            size="sm"
            @click="router.push('/operations')"
          />
        </div>
      </template>

      <div v-if="operations.length" class="divide-y divide-muted">
        <div
          v-for="op in operations.slice(0, 3)"
          :key="op.id"
          class="py-3 flex items-center justify-between text-sm"
        >
          <div class="flex items-center gap-3 min-w-0">
            <code class="text-xs font-bold text-label font-mono">{{ op.action }}</code>
            <span class="text-xs text-muted truncate">
              {{ servers.find(s => s.id === op.server_id)?.name || op.server_id }}
            </span>
          </div>

          <div class="flex items-center gap-3">
            <B24Badge
              :label="op.status === 'succeeded' ? 'Выполнено' : op.status === 'running' ? 'Выполняется' : op.status === 'failed' ? 'Ошибка' : 'В очереди'"
              :color="op.status === 'succeeded' ? 'air-primary-success' : op.status === 'running' ? 'air-primary' : op.status === 'failed' ? 'air-primary-alert' : 'air-primary-warning'"
              size="sm"
            />
            <span class="text-xs text-muted">
              {{ new Date(op.created_at).toLocaleTimeString('ru-RU', { hour: '2-digit', minute: '2-digit' }) }}
            </span>
          </div>
        </div>
      </div>
      <div v-else class="py-4 text-center text-sm text-muted">
        Операций пока нет
      </div>
    </B24Card>

    <!-- Dialogs -->
    <AddServerDialog
      v-model:open="addOpen"
      @created="handleServerCreated"
    />

    <ActionDialog
      v-if="selected && activeAction"
      v-model:open="actionDialogOpen"
      :server="selected"
      :capability="activeAction"
      @executed="handleActionExecuted"
    />
  </div>
</template>
